# Generated by Django 4.1.7 on 2023-04-24 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadimage",
            name="image",
            field=models.ImageField(
                upload_to="images",
                validators=[django.core.validators.validate_image_file_extension],
            ),
        ),
    ]
